name: Actions Readme Feed

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1.7.0
        id: feed
        with:
          url: 'https://andrewstiefel.com/feed.xml'
          file: 'README.md'
          format: '- [${title}](${url})'
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
